{% set name = "composio" %}
{% set version = "0.21.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/composio-{{ version }}.tar.gz
  sha256: 334fbcc2358467a2eed7e04133fdd9080cf63007e53caffa50555023724e956a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - requests >=2.32.2
    - urllib3 >=2
    - jsonschema >=4.23.0
    - json-schema-to-pydantic >=0.4.11
    - python >={{ python_min }},<4.0
    - pysher >=1.0.8
    - pydantic >=2.11.9
    - composio-client ==1.43.0
    - typing_extensions >=4.16.0
    - openai >=2.48.0

test:
  imports:
    - composio
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/composiohq/composio
  summary: SDK for integrating Composio with your applications.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
