{% set name = "composio" %}
{% set version = "0.8.19" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/composio-{{ version }}.tar.gz
  sha256: 61314dc1b14fd3e759f8570864b1dbe81a0a30c7d822128a90597b685f471066

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<4.0
    - pysher >=1.0.8
    - pydantic >=2.6.4
    - composio-client >=1.10.0
    - typing_extensions >=4.0.0
    - openai

test:
  imports:
    - composio
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/composiohq/composio
  summary: SDK for integrating Composio with your applications.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
