{% set name = "composio" %}
{% set version = "0.10.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/composio-{{ version }}.tar.gz
  sha256: 7c504c7357ef6e5cbc18054d56dd0870ce3865a82bea5e35d4f09cb96705be78

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<4.0
    - pysher >=1.0.8
    - pydantic >=2.6.4
    - composio-client >=1.20.0
    - typing_extensions >=4.0.0
    - openai

test:
  imports:
    - composio
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/composiohq/composio
  summary: SDK for integrating Composio with your applications.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
